### ISSUE TITLE
How to implement with resnet backbone?

### ISSUE THREAD

**Issue by LanchJL** [akhilpm/WSDDN#1]
Your results show good performance with resnet18 and resnet50, however there is no resnet implementation in the code. Do you prepare to release related code? Please do so and let me know! many thanks!!

**Comment by akhilpm** [comment]
Hi, this is a work in progress. I will be back to this after my current deadline. But for resnet backbone, you practically don't change much. Just use layers upto 4 as backbone features, then an ROI Pool and then extract proposal features for each proposal using layer 5. Here is a reference you can check. https://github.com/loolzaaa/faster-rcnn-pytorch/blob/master/lib/model/resnet.py

**Comment by LanchJL** [comment]
Very thanks for your answer！
